name: flutter drive
on: [push, pull_request]
jobs:
  android-integration-test:
    name: run integration test on Android emulator
    runs-on: "macos-latest"
    strategy:
      matrix:
        device:
          - "pixel"
          - "pixel_xl"
          - "pixel_c"
          - "Nexus 6"
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            ./scripts/setenv.sh
            cd ./organia-app
            flutter pub get
            flutter test 