name: Flutter_Integration_Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"

      - name: Restore packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test integration_test --coverage
      
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash -t "c0786a6e-1109-450b-8c27-bf6b315acba5"
        shell: bash